Add Python version of the benchmark.
dealii/code-gallery pull request #97
Opened 2022-02-15 18:05 UTC by bangerth

The promised follow-up to #96 with the Python code. I'll put the Matlab version up in a separate PR.

2022-02-16 19:06 UTC, bangerth commented
To make everyone's life simpler, I added the Matlab version here as well.

@davidaristoff: FYI

2022-02-22 03:14 UTC, bangerth commented
Ping?

2022-02-22 03:56 UTC, marcfehling requested changes
I'm neither expert in Matlab or python, so it would be nice if another pair of eyes could go over it.

The Matlab version has a `plot_solution.m` file to show the solution as a surface plot. Do you think such a feature would be good to have in the python implementation as well?

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/forward_solver.m
> +        thet = theta(floor(i/4)+1,floor(j/4)+1);
I would choose a more descriptive name. Maybe `theta_loc`, which would be the equivalent to `A_loc`?

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Python/forward_solver.py
> +            thet = theta[int(i/4)+int(j/4)*8]
See above.

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Readme.md
> +            A[np.ix_(dof,dof)] += thet*A_loc
See above.

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/plot_solution.m
> +        thet = theta(floor(i/4)+1,floor(j/4)+1);
See above.

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/plot_solution.m
> +U = A\b;
That code looks exactly like the one in `forward_solver.m`. Can you call `forward_solver` instead?

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/plot_solution.m
> +surf(xsp,xsp,zs)
```suggestion
surf(xsp,xsp,zs)

```

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/forward_solver.m
> +
```suggestion
```

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/get_statistics.m
> +%autocov = mean of autocovariance matrix over all the chains
```suggestion
%autocovar = mean of autocovariance matrix over all the chains
```

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/get_statistics.m
> +for n=1:N                            %loop over independent Markov chains
```suggestion
for n=1:N    %loop over independent Markov chains
```

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/get_statistics.m
> +
```suggestion
```

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Matlab/main.m
> +theta_means = zeros(8,8,N);      %overall mean of theta
You use three whitespaces in other occasions.
```suggestion
data = zeros(8,8,L,N);        %data matrix of samples at lag times
theta_means = zeros(8,8,N);   %overall mean of theta
```

2022-02-22 03:56 UTC, marcfehling commented on MCMC-Laplace/Python/forward_solver.py
> +    for i in range(n_runs) :
The Matlab version uses [`parfor`](https://www.mathworks.com/help/parallel-computing/parfor.html) on this loop in `main.m`. Of course, then you can't really compare runtimes between the Matlab and the python code.

You can try to run the computations with `multiprocessing` package to provide basic loop parallelization. Maybe [`Pool`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool) would work well.

2022-02-22 04:55 UTC, bangerth commented
@davidaristoff Can you take a look at these suggestions? If you make these changes in your repository, I will pull the latest code from there and make corresponding changes to the python version.

2022-02-22 04:56 UTC, bangerth commented on MCMC-Laplace/Python/forward_solver.py
> +    for i in range(n_runs) :
No, the point is to just time a few runs. I'd rather keep things simple.

2022-02-22 05:10 UTC, marcfehling commented
> @davidaristoff Can you take a look at these suggestions? If you make these changes in your repository, I will pull the latest code from there and make corresponding changes to the python version.

It's really just renaming one or two variables and some layout suggestions :)

2022-02-22 17:20 UTC, davidaristoff commented on MCMC-Laplace/Python/forward_solver.py
> +    for i in range(n_runs) :
Guys, I didn't actually use "parfor" when I compared run times. The forward solver takes <5 milliseconds on my MacBook Pro without "parfor". You can choose the number of workers in main.m, and nothing precludes using only 1.

2022-02-22 17:22 UTC, davidaristoff commented on MCMC-Laplace/Matlab/forward_solver.m
> +        thet = theta(floor(i/4)+1,floor(j/4)+1);
Sure. I'll change that.

2022-02-22 17:24 UTC, davidaristoff commented on MCMC-Laplace/Matlab/main.m
> +theta_means = zeros(8,8,N);      %overall mean of theta
I don't recall counting whitespaces ever... :)

2022-02-22 17:30 UTC, davidaristoff commented on MCMC-Laplace/Matlab/plot_solution.m
> +U = A\b;
I will need forward_solver to return the coefficient vector U in addition to the measurement vector z. 

Let me make sure this doesn't create a substantial dent into runtime. I don't anticipate it will.

2022-02-22 17:34 UTC, davidaristoff approved these changes

2022-02-22 17:44 UTC, bangerth commented on MCMC-Laplace/Matlab/plot_solution.m
> +U = A\b;
Then don't do it. The forward solver should compute Z, not U. I would say just ignore @marcfehling 's comment here -- I think the design you had for the forward solver is as it is.

2022-02-22 17:48 UTC, davidaristoff commented on MCMC-Laplace/Matlab/plot_solution.m
> +U = A\b;
OK, I'll leave it alone, then.

2022-02-22 18:05 UTC, davidaristoff commented
Do I have to approve a pull request? I'm not really familiar with Github...

2022-02-22 18:33 UTC, bangerth commented
No. In this case, I created this pull request using the software I had pulled from your repo. Once you tell me that I should get the version from your repo again, I will do so, update the version shown here, and someone else will merge.

2022-02-23 05:08 UTC, bangerth commented
I've imported @davidaristoff 's last version, and have made the corresponding changes in the python version. Any more comments?

2022-02-23 05:10 UTC, marcfehling approved these changes

2022-02-23 05:10 UTC, marcfehling commented
I couldn't find a way to plot the solution in the python code. The Matlab implementation provides one.

Do you think such a feature would be nice for the python code?

2022-02-23 05:16 UTC, bangerth commented
No, it's unimportant. If someone wants to do it, they can use the Matlab version, or they can add this feature later -- but it's not the point of the program as it stands right now. The point of the code is to provide a Python version to compute the posterior probability, nothing else.

2022-02-26 01:59 UTC, bangerth commented
Ping?

2022-02-26 02:00 UTC, merged